server:
  port: 8080

spring:
  application:
    name: bpm-inteligente-core
  data:
    mongodb:
      uri: mongodb+srv://diegogarciacab18_db_user:SrJEy1wMp7IxDpH2@sistemaworkflowdb.xbal0oe.mongodb.net/bpm_db?retryWrites=true&w=majority
      auto-index-creation: true

logging:
  level:
    com.bpm.inteligente: DEBUG
    org.springframework.data.mongodb: INFO
