server:
  port: 8080

spring:
  application:
    name: bpm-inteligente-core
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/bpm_inteligente}
      auto-index-creation: true

logging:
  level:
    com.bpm.inteligente: DEBUG
    org.springframework.data.mongodb: INFO
